version: 0.1.0+{build}

image: Visual Studio 2017

build_script:
- ps: dotnet build

test_script:
- ps: >-
    cd ./argparse.UnitTests/
    dotnet opencover -register:user -target:xunit.console -targetargs:"argparse.UnitTests.csproj /appveyor" -filter:"+[*]* -[xunit*]*" -output:coveragereport.xml