version: 1.0.0+{build}
image: Visual Studio 2017

install:
- ps: choco install codecov

build_script:
- ps: >-
    dotnet restore

    dotnet build

test_script:
- ps: >-
    cd ./argparse.UnitTests/

    dotnet opencover -register:user -target:dotnet.exe -targetargs:"test argparse.UnitTests.csproj" -filter:"+[*]* -[xunit*]*" -output:coveragereport.xml

    codecov -f coveragereport.xml